### PR TITLE
Python versions iso_dateformat scenario

### LINKED ISSUE #46: [pip-rating The Lord of the Words]Error ISO dateformat with click dependecy ?
### Context
Congrats on the project and the great lighting talk at PyConES2023 !
Really great project.  Thanks for contributing to the community. Keep the great work up! 👍 
I´m testing out under the context of [The Lord of The Words project](https://github.com/SoyGema/The-Lord-of-The-Words-The-two-frameworks/blob/main/requirements.txt)

So I go to the project folder after` pip install pip-rating`
and run
```bash
$ pip-rating 
```

 

### Hypothesis 
`click` isodate format working

### Actual behavior

It does indeed start analyzing dependencies, but at some point it shows the following error. 
Posting here full-trace 
```
(.torchenv) pip-rating
Autodetected requirements file: requirements.txt
Traceback (most recent call last):
  File "/Users/gema/miniconda3/bin/pip-rating", line 8, in <module>
    sys.exit(manage())
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/management.py", line 206, in manage
    catch(cli)()
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/exceptions.py", line 45, in wrap
    fn(*args, **kwargs)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/management.py", line 77, in cli
    ctx.invoke(analyze_file, file=str(req_file.path))
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/management.py", line 160, in 
analyze_file
    results.show_results(dependencies, format_name)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/results.py", line 294, in 
show_results
    self.show_packages_results(dependencies)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/results.py", line 307, in 
show_packages_results
    global_rating_score = self.get_global_rating_score(dependencies)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/results.py", line 277, in 
get_global_rating_score
    global_rating_score = dependencies.get_global_rating_score()
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/dependencies.py", line 139, in 
get_global_rating_score
    global_rating_score = package.rating.get_global_rating_score()
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/rating.py", line 322, in 
get_global_rating_score
    [self.get_rating_score(from_package)]
  File "/Users/../miniconda3/lib/python3.10/site-packages/pip_rating/rating.py", line 318, in 
get_rating_score
    return self.rating_score
  File "/Users/../miniconda3/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/../miniconda3/lib/python3.10/site-packages/pip_rating/rating.py", line 291, in 
rating_score
    scores = dict(self.breakdown_scores).values()
  File "/Users/gema/miniconda3/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/../miniconda3/lib/python3.10/site-packages/pip_rating/rating.py", line 277, in 
breakdown_scores
    return [
  File "/Users/.../miniconda3/lib/python3.10/site-packages/pip_rating/rating.py", line 278, in <listcomp>
    (breakdown.breakdown_key, breakdown.get_score(self))
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/pip_rating/rating.py", line 146, in get_score
    dt = datetime.datetime.fromisoformat(iso_dt)
ValueError: Invalid isoformat string: '2023-09-14T18:56:29.702900Z'
```
### Interpretation
I´m still getting familiarized with some details, but what I´m understanding ( please, don´t hesitate to tell me if I´m wrong or pointing me out to the right direction ) is that this might be related with [click](https://pypi.org/project/click/) date conversion somehow? 
The mental model under the `click` choice hypothesis is based on part of the following trace, but I might be wrong!
```
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gema/miniconda3/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
```

When I go [here](https://github.com/Nekmo/pip-rating/blob/eeaec2dbd44ca3516e59f62cee28658e6ad26490/pip_rating/rating.py#L142) , what Im understanding is that you are trying to use a delta-time to determine somehow a "time-trusted-score" based on when was it updated and now?

### Traceback

_No response_

### Info
pip-rating 0.2.1
  🔝 This is the latest version.
  🐍 Python version: 3.10.10
  💻 Platform: macOS-13.4.1-arm64-arm-64bit

### Other details

I really found useful the tool verbosity, as I could see that It was going down in the analysis.
Congrats for bringing transparency to OSS maintenance! 

### Checklist

- [X] The error is in the project's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U pip-rating` and triggered the bug in the latest version.

### PR DESCRIPTION
**Pull request by SoyGema**
### What does this PR do?
Thanks for creating `pip-rating` and for the 𝚝𝚒𝚖𝚎 𝚝𝚛𝚊𝚟𝚎𝚕
 ride.
This pull request aims to Fix #46 

- It includes a script called `utils.py` that defines `parse_iso_datetime`,
converting date inside a Python-dependent scenario.

- It includes the function `parse_iso_datetime` into `rating.py`
- Ir drafts a discussion / ask for help about tests

- [x] Read the contributor guideline
- [x] Discussed with maintainer 
- [x] Does this PR have tests ? 

### Tests 
It would be amazing if you could give me a helping hand with this.
Please note my limited experience on this, as I'm used to putting examples for the test and I don´t know if is better to have another abstraction layer. 
🙏Thanks in advance for your empathy on this dimension. 🙏
Happy if I could learn more about this! 
So the approach that I would do is, add this code under `tests>source>test_rating.py`

```
from pip_rating.utils import parse_iso_datetime  # Import the function to be tested

class TestParseIsoDatetime(unittest.TestCase):
    def test_python_311_or_higher(self):
        # Test with Python 3.11 or higher
        from sys import version_info
        version_info = (3, 11)  # Simulate Python 3.11
        expected_dt = datetime.datetime(2023, 9, 14, 18, 56, 29, 702900, tzinfo=datetime.timezone.utc)
        iso_dt = '2023-09-14T18:56:29.702900Z'
        result = parse_iso_datetime(iso_dt)
        self.assertEqual(result, expected_dt)

    def test_python_310_or_lower(self):
        # Test with Python 3.10 or lower
        from sys import version_info
        version_info = (3, 10)  # Simulate Python 3.10
        expected_dt = datetime.datetime(2023, 9, 14, 18, 56, 29, 702900, tzinfo=datetime.timezone.utc)
        iso_dt = '2023-09-14T18:56:29.702900Z'
        result = parse_iso_datetime(iso_dt)
        self.assertEqual(result, expected_dt)
```

### Possible discussions

1. Is it ok to put `utils.py` under` pip_rating` ? Unclear to me at some point if it could be in `sources`
2. Tests
3. Conclusions about time travel with Python versions and datetime formats 😇

### Lore Follow up

delorean-time-clock-back-to-the-future

**𝙼𝚊𝚛𝚝𝚢**: 𝙳𝚘𝚌, 𝚝𝚑𝚒𝚜 𝙸𝚂𝙾 𝚍𝚊𝚝𝚎 𝚏𝚘𝚛𝚖𝚊𝚝 𝚝𝚑𝚒𝚗𝚐 𝚒𝚜 𝚍𝚛𝚒𝚟𝚒𝚗𝚐 𝚖𝚎 𝚗𝚞𝚝𝚜! 𝚂𝚘𝚖𝚎𝚝𝚒𝚖𝚎𝚜 𝚒𝚝'𝚜 '𝟸0𝟸𝟹-0𝟿-𝟷𝟺𝚃𝟷𝟾:𝟻𝟼:𝟸𝟿.𝟽0𝟸𝟿00𝚉,' 𝚊𝚗𝚍 𝚘𝚝𝚑𝚎𝚛 𝚝𝚒𝚖𝚎𝚜, 𝚒𝚝'𝚜 𝚓𝚞𝚜𝚝 '𝟸0𝟸𝟹-0𝟿-𝟷𝟺𝚃𝟷𝟾:𝟻𝟼:𝟸𝟿𝚉'! 𝙷𝚘𝚠 𝚍𝚘 𝙸 𝚎𝚟𝚎𝚗 𝚙𝚊𝚛𝚜𝚎 𝚝𝚑𝚒𝚜?

**𝙳𝚘𝚌**: 𝙶𝚛𝚎𝚊𝚝 𝚂𝚌𝚘𝚝𝚝, 𝙼𝚊𝚛𝚝𝚢! 𝙸𝚝'𝚜 𝚕𝚒𝚔𝚎 𝚠𝚎'𝚛𝚎 𝚍𝚎𝚊𝚕𝚒𝚗𝚐 𝚠𝚒𝚝𝚑 𝚝𝚒𝚖𝚎 𝚝𝚛𝚊𝚟𝚎𝚕 𝚑𝚎𝚛𝚎. 𝚈𝚘𝚞 𝚜𝚎𝚎, 𝚒𝚗 𝙿𝚢𝚝𝚑𝚘𝚗, 𝚒𝚝'𝚜 𝚊𝚕𝚕 𝚊𝚋𝚘𝚞𝚝 𝚍𝚒𝚏𝚏𝚎𝚛𝚎𝚗𝚝 𝚟𝚎𝚛𝚜𝚒𝚘𝚗𝚜 𝚊𝚗𝚍 𝚍𝚊𝚝𝚎 𝚏𝚘𝚛𝚖𝚊𝚝𝚜. 𝙸𝚗 𝚝𝚑𝚎 𝚙𝚊𝚜𝚝, 𝚝𝚑𝚎𝚢 𝚍𝚒𝚍𝚗'𝚝 𝚑𝚊𝚟𝚎 𝚝𝚑𝚎 𝚏𝚊𝚗𝚌𝚢 𝚏𝚛𝚘𝚖𝚒𝚜𝚘𝚏𝚘𝚛𝚖𝚊𝚝, 𝚊𝚗𝚍 𝚝𝚑𝚎𝚢 𝚞𝚜𝚎𝚍 𝚝𝚑𝚎 𝚍𝚊𝚝𝚎𝚞𝚝𝚒𝚕 𝚕𝚒𝚋𝚛𝚊𝚛𝚢 𝚝𝚘 𝚖𝚊𝚔𝚎 𝚜𝚎𝚗𝚜𝚎 𝚘𝚏 𝚒𝚝 𝚊𝚕𝚕.

**𝙼𝚊𝚛𝚝𝚢**: 𝚂𝚘, 𝚠𝚑𝚊𝚝 𝚍𝚘 𝙸 𝚍𝚘 𝚗𝚘𝚠? 𝙸 𝚍𝚘𝚗'𝚝 𝚠𝚊𝚗𝚝 𝚝𝚘 𝚋𝚛𝚎𝚊𝚔 𝚝𝚑𝚎 𝚜𝚙𝚊𝚌𝚎-𝚝𝚒𝚖𝚎 𝚌𝚘𝚗𝚝𝚒𝚗𝚞𝚞𝚖!

**𝙳𝚘𝚌**: 𝙳𝚘𝚗'𝚝 𝚠𝚘𝚛𝚛𝚢, 𝙼𝚊𝚛𝚝𝚢. 𝚆𝚎'𝚟𝚎 𝚐𝚘𝚝 𝚊 𝚌𝚘𝚗𝚍𝚒𝚝𝚒𝚘𝚗𝚊𝚕 𝚝𝚒𝚖𝚎 𝚖𝚊𝚌𝚑𝚒𝚗𝚎 – 𝙸 𝚖𝚎𝚊𝚗, 𝚌𝚘𝚍𝚎 – 𝚝𝚑𝚊𝚝 𝚌𝚑𝚎𝚌𝚔𝚜 𝚢𝚘𝚞𝚛 𝙿𝚢𝚝𝚑𝚘𝚗 𝚟𝚎𝚛𝚜𝚒𝚘𝚗 𝚊𝚗𝚍 𝚙𝚒𝚌𝚔𝚜 𝚝𝚑𝚎 𝚛𝚒𝚐𝚑𝚝 𝚖𝚎𝚝𝚑𝚘𝚍. 𝙸𝚏 𝚢𝚘𝚞'𝚛𝚎 𝚒𝚗 𝙿𝚢𝚝𝚑𝚘𝚗 𝟹.𝟷𝟷 𝚘𝚛 𝚑𝚒𝚐𝚑𝚎𝚛, 𝚒𝚝 𝚐𝚘𝚎𝚜 '𝚏𝚛𝚘𝚖𝚒𝚜𝚘𝚏𝚘𝚛𝚖𝚊𝚝' 𝚍𝚒𝚛𝚎𝚌𝚝𝚕𝚢. 𝙵𝚘𝚛 𝚘𝚕𝚍𝚎𝚛 𝚟𝚎𝚛𝚜𝚒𝚘𝚗𝚜, 𝚒𝚝 𝚝𝚛𝚒𝚎𝚜 '𝚏𝚛𝚘𝚖𝚒𝚜𝚘𝚏𝚘𝚛𝚖𝚊𝚝' 𝚏𝚒𝚛𝚜𝚝 𝚊𝚗𝚍 𝚝𝚑𝚎𝚗 𝚏𝚊𝚕𝚕𝚜 𝚋𝚊𝚌𝚔 𝚝𝚘 𝚍𝚊𝚝𝚎𝚞𝚝𝚒𝚕.

**𝙼𝚊𝚛𝚝𝚢**: 𝚃𝚑𝚊𝚝'𝚜 𝚑𝚎𝚊𝚟𝚢, 𝙳𝚘𝚌. 𝙱𝚞𝚝 𝚠𝚑𝚊𝚝 𝚊𝚋𝚘𝚞𝚝 𝚝𝚑𝚎 𝚏𝚞𝚝𝚞𝚛𝚎?

**𝙳𝚘𝚌**: 𝙸𝚗 𝚝𝚑𝚎 𝚏𝚞𝚝𝚞𝚛𝚎, 𝚠𝚑𝚎𝚗 𝚎𝚟𝚎𝚛𝚢𝚘𝚗𝚎'𝚜 𝚘𝚗 𝙿𝚢𝚝𝚑𝚘𝚗 𝟹.𝟷𝟷 𝚘𝚛 𝚑𝚒𝚐𝚑𝚎𝚛, 𝚢𝚘𝚞 𝚌𝚊𝚗 𝚍𝚒𝚝𝚌𝚑 𝚝𝚑𝚎 𝚏𝚊𝚕𝚕𝚋𝚊𝚌𝚔 𝚌𝚘𝚍𝚎. 𝚄𝚗𝚝𝚒𝚕 𝚝𝚑𝚎𝚗, 𝚓𝚞𝚜𝚝 𝚔𝚎𝚎𝚙 𝚝𝚑𝚎 𝙳𝚎𝙻𝚘𝚛𝚎𝚊𝚗 – 𝙸 𝚖𝚎𝚊𝚗, 𝚌𝚘𝚍𝚎 – 𝚛𝚞𝚗𝚗𝚒𝚗𝚐 𝚜𝚖𝚘𝚘𝚝𝚑𝚕𝚢.

**𝙼𝚊𝚛𝚝𝚢**: 𝚃𝚑𝚊𝚗𝚔𝚜, 𝙳𝚘𝚌. 𝙸 𝚐𝚞𝚎𝚜𝚜 𝙸'𝚕𝚕 𝚜𝚝𝚒𝚌𝚔 𝚝𝚘 𝚝𝚑𝚒𝚜 𝚝𝚒𝚖𝚎-𝚝𝚛𝚊𝚟𝚎𝚕𝚒𝚗𝚐 𝚌𝚘𝚍𝚎 𝚏𝚘𝚛 𝚗𝚘𝚠!

### CODE REVIEW

**Comment by Nekmo** [comment]
Hi @SoyGema , thank you again for your help!

For tests conditioned by the Python version number, you can use the `skipIf` method, so it will only be checked depending on the Python version in use. Since the tests in GitHub Actions are verified with all supported versions, both methods will be verified:
https://docs.python.org/3/library/unittest.html#skipping-tests-and-expected-failures
There is no `test_utils.py` file for the tests of `utils.py` yet, but you can create one in `tests/test_utils.py`.

To be able to use the `dateutils` module in Python 3.10 and earlier, it is necessary to add it to the *requirements* file, in case the user does not have the module installed. To do this, it is necessary to modify the `requirements.in` file and then run `pip-compile` (you need to install `pip-tools` first using `pip install pip-tools`!).

However, not all users need this dependency, only users with a version prior to Python 3.11. To do this, the best thing would be to include a line like the following: `python-dateutil>=2.8.1; python_version < '3.11'`. Remember that in your code, only `dateutil` should be imported for Python 3.10, so you should change the import to the conditional that Python 3.10 uses.
```
def parse_iso_datetime(iso_dt):
    if sys.version_info >= (3, 11):
        ...
    else:
        from dateutil import parser as dateutil_parser
        try:
            dt = datetime.fromisoformat(iso_dt)
        except ValueError:
            dt = dateutil_parser.isoparse(iso_dt)
    return dt
```

I have seen that the GitHub Actions lint is failing due to black validation. Remember to run `black` in your environment! If you use pre-commit, it is enabled automatically. If not, don't worry, I can check it and take care of it myself.
https://github.com/Nekmo/pip-rating/blob/master/.pre-commit-config.yaml
https://black.readthedocs.io/en/stable/getting_started.html

I know it's a lot to do, but don't worry, we're almost done. I think this should be all we need for the Pull Request. Likewise, I hope I was able to help, if you have any questions, let me know. Thanks for your contribution!

**Marty:** `Doc, I'm starting to think that this ISO date format thing is a conspiracy by the future to keep us from traveling back in time.`

**Doc:** `That's a very interesting theory, Marty. But I think it's more likely that it's just a result of the different ways that Python has evolved over time.`

**Marty:** `Maybe. But I'm not so sure. I've been seeing some strange things lately. Like the other day, I saw a DeLorean parked in the driveway next to my house. But when I went to investigate, it was gone.`

**Doc:** `Marty, you're not imagining things, are you?`

**Marty:** `I don't know, Doc. But I'm starting to think that the future is closer than we think.`

**Doc:** `Well, if that's the case, we need to be prepared. We need to make sure that our code is ready for anything.`

**Marty:** `I'm on it, Doc. I'm going to start working on a new version of the DeLorean code that can handle any date format, past, present, or future.`

**Doc:** `Good luck, Marty. And be careful. The space-time continuum is a delicate thing.`

**Marty:** `I will, Doc. I will.`

**Comment by Nekmo** [comment]
> Hey! Please confirm that all is correct and confirm if I'm missing something ? :
> 
> * [ ]  Change import dateutil in function [aab358b](https://github.com/Nekmo/pip-rating/commit/aab358bad08402fdd569f10bb14856deff38f334)
> * [ ]  Create `test_utils.py` add tests with skipIf ( first time Im doing this ) Sorry I copy pasted from other test file and the commit is far from clean ...  see the [file](https://github.com/Nekmo/pip-rating/pull/47/files#diff-33c13e0b177bacd2f02e29bcb8aea5b49e7ce34901fd8f41fefb65defba1bd33)
> * [ ]  Modified `requirements.in`  [40c54ab](https://github.com/Nekmo/pip-rating/commit/40c54ab3845fe65f73c78266bb7f5bf861754764)
> 
> Can you take care of black ? Can you please send me more information about this so I can learn ? black is some sort of prettier reformat ?

Yes, this is correct :) 

Remember that after adding the dependency to the `requirements.in` file, you must run `pip-compile`. This command will also update the `requirements.txt` file.

Black is a tool that checks if the code complies with the style guide. It automatically rewrites the code if it detects invalid code. You have integrations for different IDEs, but you can also run it manually using:
```
$ black <file_or_folder>
```

Install it using `Pypi`:
```
$ pip install black
```

**Comment by SoyGema** [comment]
Hello there @Nekmo ! As noted, I runed `pip-compile ` in 62eeb55 and black in 2f8edd1 

```
(base) ➜  pip_rating git:(python_version_iso_dateformat) black rating.py 
reformatted rating.py

All done! ✨ 🍰 ✨
1 file reformatted.
```
It´s so exciting this is moving forward! 
Let me know if there´s something else I´m missing.

Learned a few things thanks to this PR, so thanks for giving me the opportunity to contribute. Thanks also for your guidance and support. Your empathy toward supporting contributors' growth affirms your commitment to the community.
Besides, all Lore has been fun and inspiring, and even though it can be seen as unexpected or abnormal, it really aligns with the contributions OSS values that [research studies Fig2](https://arxiv.org/pdf/2101.10291.pdf) show .  Thanks for embodying help through learning, reciprocity, and fun.  


Captura de pantalla 2023-10-14 a las 10 51 21

**Comment by Nekmo** [comment]
Many thanks to you @SoyGema for your help! I'm glad to know that the experience has helped you :) I've re-run the tests for the PR, and as far as I can tell, black would need to be run on the files `utils.py` and `test_utils.py`.
https://github.com/Nekmo/pip-rating/actions/runs/6516639916/job/17704754903?pr=47

 I need to check how to enable Github Actions tests for Pull Requests... Sorry for the inconvenience!

**Marty:** `But why do we have to run black every time?`
**Doc:** `If we had used black from the beginning, we wouldn't have had to travel back in time to fix the problem in the future.`
**Marty:** `But then... we wouldn't have traveled back in time, and we wouldn't have had a movie.`
**Doc:** `That's also true.`

**Comment by SoyGema** [comment]
Hey,
No worries at all.  
Please check if the `three-black-problem` works now. 


Captura de pantalla 2023-10-14 a las 19 30 49


𝙼𝚊𝚛𝚝𝚢: 𝚈𝚘𝚞 𝚔𝚗𝚘𝚠, 𝙳𝚘𝚌, 𝚝𝚑𝚒𝚜 𝚓𝚘𝚞𝚛𝚗𝚎𝚢 𝚝𝚑𝚛𝚘𝚞𝚐𝚑 𝚝𝚑𝚎 𝚠𝚘𝚛𝚕𝚍 𝚘𝚏 𝙿𝚢𝚝𝚑𝚘𝚗 𝚊𝚗𝚍 𝙸𝚂𝙾 𝚍𝚊𝚝𝚎 𝚙𝚊𝚛𝚜𝚒𝚗𝚐 𝚖𝚊𝚍𝚎 𝚖𝚎 𝚊𝚙𝚙𝚛𝚎𝚌𝚒𝚊𝚝𝚎 𝚝𝚑𝚎 𝚙𝚘𝚠𝚎𝚛 𝚘𝚏 𝚊𝚍𝚊𝚙𝚝𝚊𝚋𝚒𝚕𝚒𝚝𝚢 𝚊𝚗𝚍 𝚝𝚑𝚎 𝚟𝚊𝚕𝚞𝚎 𝚘𝚏 𝚐𝚘𝚘𝚍 𝚘𝚕𝚍-𝚏𝚊𝚜𝚑𝚒𝚘𝚗𝚎𝚍 𝚙𝚛𝚘𝚋𝚕𝚎𝚖-𝚜𝚘𝚕𝚟𝚒𝚗𝚐.

𝙳𝚘𝚌:  𝚈𝚘𝚞'𝚟𝚎 𝚐𝚛𝚘𝚠𝚗, 𝙼𝚊𝚛𝚝𝚢. 𝙰𝚗𝚍 𝚛𝚎𝚖𝚎𝚖𝚋𝚎𝚛, 𝚒𝚗 𝚝𝚑𝚎 𝚠𝚘𝚛𝚕𝚍 𝚘𝚏 𝚙𝚛𝚘𝚐𝚛𝚊𝚖𝚖𝚒𝚗𝚐, 𝚎𝚟𝚎𝚛𝚢 𝚌𝚑𝚊𝚕𝚕𝚎𝚗𝚐𝚎 𝚢𝚘𝚞 𝚌𝚘𝚗𝚚𝚞𝚎𝚛 𝚋𝚛𝚒𝚗𝚐𝚜 𝚢𝚘𝚞 𝚘𝚗𝚎 𝚜𝚝𝚎𝚙 𝚌𝚕𝚘𝚜𝚎𝚛 𝚝𝚘 𝚋𝚎𝚌𝚘𝚖𝚒𝚗𝚐 𝚊 𝚝𝚛𝚞𝚎 𝚌𝚘𝚍𝚎 𝚝𝚒𝚖𝚎 𝚝𝚛𝚊𝚟𝚎𝚕𝚕𝚎𝚛.

𝙼𝚊𝚛𝚝𝚢:  𝚃𝚑𝚊𝚗𝚔𝚜, 𝙳𝚘𝚌. 𝚈𝚘𝚞'𝚛𝚎 𝚗𝚘𝚝 𝚓𝚞𝚜𝚝 𝚊 𝚐𝚛𝚎𝚊𝚝 𝚜𝚌𝚒𝚎𝚗𝚝𝚒𝚜𝚝; 𝚢𝚘𝚞'𝚛𝚎 𝚊 𝚐𝚛𝚎𝚊𝚝 𝚝𝚎𝚊𝚌𝚑𝚎𝚛, 𝚝𝚘𝚘.

𝙳𝚘𝚌:  𝙸𝚝'𝚜 𝚋𝚎𝚎𝚗 𝚊𝚗 𝚒𝚗𝚌𝚛𝚎𝚍𝚒𝚋𝚕𝚎 𝚊𝚍𝚟𝚎𝚗𝚝𝚞𝚛𝚎, 𝙼𝚊𝚛𝚝𝚢. 𝙱𝚞𝚝 𝚗𝚘𝚠, 𝚒𝚝'𝚜 𝚝𝚒𝚖𝚎 𝚝𝚘 𝚕𝚎𝚝 𝚢𝚘𝚞 𝚏𝚕𝚢 𝚘𝚗 𝚢𝚘𝚞𝚛 𝚘𝚠𝚗, 𝚠𝚒𝚝𝚑 𝚌𝚘𝚍𝚎 𝚊𝚜 𝚢𝚘𝚞𝚛 𝚝𝚛𝚞𝚜𝚝𝚢 𝚌𝚘𝚖𝚙𝚊𝚗𝚒𝚘𝚗.

𝙼𝚊𝚛𝚝𝚢:  𝙶𝚘𝚘𝚍𝚋𝚢𝚎, 𝙳𝚘𝚌. 𝙸'𝚕𝚕 𝚔𝚎𝚎𝚙 𝚎𝚡𝚙𝚕𝚘𝚛𝚒𝚗𝚐 𝚝𝚑𝚎 𝚝𝚒𝚖𝚎 𝚊𝚗𝚍 𝚜𝚙𝚊𝚌𝚎 𝚘𝚏 𝚌𝚘𝚍𝚎, 𝚊𝚗𝚍 𝙸'𝚕𝚕 𝚗𝚎𝚟𝚎𝚛 𝚏𝚘𝚛𝚐𝚎𝚝 𝚝𝚑𝚎 𝚕𝚎𝚜𝚜𝚘𝚗𝚜 𝙸'𝚟𝚎 𝚕𝚎𝚊𝚛𝚗𝚎𝚍 𝚑𝚎𝚛𝚎.

𝙳𝚘𝚌:  𝙵𝚊𝚛𝚎𝚠𝚎𝚕𝚕, 𝙼𝚊𝚛𝚝𝚢! 𝚁𝚎𝚖𝚎𝚖𝚋𝚎𝚛, 𝚝𝚑𝚎 𝚏𝚞𝚝𝚞𝚛𝚎 𝚒𝚜 𝚠𝚑𝚊𝚝 𝚢𝚘𝚞 𝚖𝚊𝚔𝚎 𝚘𝚏 𝚒𝚝. 𝙰𝚗𝚍 𝚠𝚑𝚘 𝚔𝚗𝚘𝚠𝚜, 𝚘𝚗𝚎 𝚍𝚊𝚢 𝚢𝚘𝚞 𝚖𝚒𝚐𝚑𝚝 𝚓𝚞𝚜𝚝 𝚛𝚎𝚠𝚛𝚒𝚝𝚎 𝚝𝚑𝚎 𝚏𝚞𝚝𝚞𝚛𝚎 𝚘𝚏 𝚙𝚛𝚘𝚐𝚛𝚊𝚖𝚖𝚒𝚗𝚐 𝚒𝚝𝚜𝚎𝚕𝚏!

𝙼𝚊𝚛𝚝𝚢:  𝙳𝚘𝚌, 𝚝𝚑𝚎 𝚌𝚘𝚍𝚎 𝚒𝚜 𝚖𝚢 𝙳𝚎𝙻𝚘𝚛𝚎𝚊𝚗. 𝚃𝚑𝚎 𝚊𝚍𝚟𝚎𝚗𝚝𝚞𝚛𝚎 𝚌𝚘𝚗𝚝𝚒𝚗𝚞𝚎𝚜.

**Comment by Nekmo** [comment]
Everything is fine, thanks! It's already merged :) I hope to be able to count on you in the future.

**Doc:** `This adventure may have ended, but it is only the beginning of new adventures. As long as we can code, we will never stop enjoying and discovering new things.`

**Marty:** `And I hope to be there so that we can discover them together.`

bttf

**Comment by Nekmo** [comment]
@SoyGema I have added you to the collaborators file. If you want me to remove you, let me know and I'll remove you :)

**Comment by SoyGema** [comment]
> @SoyGema I have added you to the collaborators file. If you want me to remove you, let me know and I'll remove you :)

Hey Thanks! That means a lot 🥹

**Pull request merged**
